### PR TITLE
Login form changed

### PR DESCRIPTION
**Pull request by Ajay055**

### CODE REVIEW

**Comment by jordanhilado** [comment]
Any reason/description for this change? @Ajay055

**Comment by Ajay055** [comment]
For improvement in frontend and participating in the hacktoberfest as I am a beginner, I hope you will consider the changes I made.

**Comment by jordanhilado** [comment]
I don't think the change is necessary, but I will accept this for hacktoberfest! Thank you! @Ajay055

**Comment by Ajay055** [comment]
Thank you! @jordanhilado

**Pull request closed without merging**
