### PR TITLE
Create Requirements.txt

### PR DESCRIPTION
**Pull request by saptarsi96**
Requirements.txt for Dockerfile to run "pip install -r requirements.txt" as per Issue #6

### CODE REVIEW

**Comment by georgettica** [comment]
thanks! incorporating to my code.

ps, your file has `Requirements.txt` not the lowercase `r`

**Comment by georgettica** [comment]
actually @saptarsi96 , when it's merged I will change my code.. currently using my old method

**Comment by saptarsi96** [comment]
Sorry my bad.

**Comment by georgettica** [comment]
ti's fine. hope yours gets merged before me

**Comment by georgettica** [comment]
@saptarsi96 you can see my PR and feel free to comment if something is understood/not flushed out

**Comment by georgettica** [comment]
@jordanhilado as I asked before, can you add the hacktoberfest tag? I would really appreciate it :)

**Pull request closed without merging**
